name: run update.js

on:
  schedule:
    - cron: '0 6-18/2 * * *' # At 00:00 on Monday

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: load script
      uses: actions/checkout@v2

    - name: set up node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: install dependencies
      run: npm install

    - name: run script
      env: 
        CAL_ID: ${{ secrets.CAL_ID }}
        CL_EMAIL: ${{ secrets.CL_EMAIL }}
        PRIV_KEY: ${{ secrets.PRIV_KEY }}
      run: node update.js
